In [ ]:
import numpy as np

print(np.__version__)

2.1.3
[1 2 3 4 5]


#### **Creating Array**
`np.`**`array`**`([])`
- creating a 1-d array using NumPy array function

`np.`**`array`**`(())`
- same but by passing a tuple

`arr = `**`array`**`([[] , []])`
- creating a 2-d array

`arr.`**`ndim`**
- check array dimension

`np.`**`array`**`([], ndmin)`
- create an array and define its min dimension

Create numpy ndarray using array() function

In [5]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Create numpy ndarray by passing a tuple

In [6]:
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


0-d array

In [7]:
arr = np.array(69)
print(arr)

69


1-d array

In [8]:
arr = np.array([0, 1, 2, 3, 4])
print(arr)

[0 1 2 3 4]


2-d array

In [18]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr)

[[1 2 3]
 [4 5 6]]


3-d array

In [19]:
arr = np.array([
    [
        [0, 1, 2],
        [3, 4, 5]
    ],
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
])

print(arr)

[[[0 1 2]
  [3 4 5]]

 [[1 2 3]
  [4 5 6]]]


Check number of dimension

In [20]:
a = np.array(69)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[0, 1, 2], [3, 4, 5]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Higher dimensional array

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


#### **Array Indexing**

`arr[0]`
- access 1-d array 

`arr[0, 1]`
- access 2-d array

`arr[0, ... , n]`
- access n-d array

Access array elements

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])
print(arr[1] + arr[2])

5
1
2
5


Access 2-d array

In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[1,2])

6


Access 3-d array

In [ ]:
arr = np.array([[[0, 1, 2],[3, 4, 5]], [[1, 2, 3],[4, 5, 6]]])

print(arr[0, 1, 2])

5


Negative indexing

In [29]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr[1, -1])

8


#### **Array Slicing**
`arr`**`[start : end : step]`**
- start is 0 by default
- end is length of array by default
- step is 1 by default

`arr[`**`startElement : endElement`**`, start : end : step]`
- : endElement is last element by default

In [72]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) # index 1 to 5
print(arr[4:]) # index 4 to end of array
print(arr[:4]) # beginning to index 4

[2 3 4 5]
[5 6 7]
[1 2 3 4]


Negative slicing

In [73]:
print(arr[-3:-1]) # last 3 to last element of the array

[5 6]


Step

In [ ]:
print(arr[1:5:2]) # every other element from index 1 to 5
print(arr[::2]) # every other element from the entire array

[2 4]


2-d array slicing

In [75]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4]) # from 2nd element, slice index 1 to 4
print(arr[0:2, 2]) # for both elements, slice index 2
print(arr[0:2, 1:4]) # for both elements, slice index 1 to 4

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


#### **Data Types**
`arr.`**`dtype`**
- check dtype

`np.`**`array`**`([], dtype='b'` or `bool)`
- create array and define its dtype 

`np.`**`array`**`([], dtype='S4')`
- create array and define its dtype and size

`arr.`**`astype`**`('b')`
- change dtype of existing array


Python data types
- strings
- integer
- float
- boolean
- complex

Numpy data types
- i (integer)
- b (boolean)
- u (unsigned integer)
- f (float)
- c (complex float)
- m (timedelta)
- M (datetime)
- O (object)
- S (string)
- U (unicode string)
- V (void; fixed chunk of memory for other types)

Checking dtype

In [ ]:
i = np.array([1, 2, 3, 4])
b = np.array([True, False])
f = np.array([1.0, 2.0, 3.0, 4.0])
U = np.array(['apple', 'banana', 'cherry'])
S = np.array([b'apple', b'banana'])

print(i.dtype)
print(b.dtype) 
print(f.dtype)
print(U.dtype) # <U6 means unicode string with max string length 6 letters
print(S.dtype) # |S6 means byte sring with max string length 6 letters

int64
bool
float64
<U6
|S6


Creating array with defined dtype and size

In [67]:
S = np.array([1, 2, 3, 4], dtype='S')
S4 = np.array([1, 2, 3, 4], dtype='S4')

print(S.dtype)
print(S4.dtype)

|S1
|S4


Converting dtype of an exising array

In [71]:
arr = np.array([1.1, 2.1, 3.1])

arr_i = arr.astype('i')
arr_int = arr.astype(int)
arr_bool = arr.astype(bool)

print(arr.dtype)
print(arr_i.dtype)
print(arr_int.dtype)
print(arr_bool.dtype)

float64
int32
int64
bool


#### **Copy vs View**
`arr.`**`copy`**`()`
- create copy of the array

`arr.`**`view`**`()`
- create view of the array

`arr_copy.`**`base`** returns None ***while*** `arr_view.`**`base`** return the base array
- check if the array owns its data

Create a copy of the array

In [79]:
arr = np.array([1, 2, 3, 4])
arr_copy = arr.copy()

arr_copy[0] = 0

print(arr)
print(arr_copy)

[1 2 3 4]
[0 2 3 4]


Create a view of the array

In [80]:
arr = np.array([1, 2, 3, 4])
arr_view = arr.view()

arr_view[0] = 0

print(arr)
print(arr_view) 

[0 2 3 4]
[0 2 3 4]


Check if the array owns its data

In [ ]:
arr = np.array([1, 2, 3, 4])

c = arr.copy()
v = arr.view()

print(c.base) # return none means it owns its data
print(v.base) # return the base data

None
[1 2 3 4]


#### **Array Shape**
`arr.shape`
- check the shape of array, depicts from outer to inner bracket

Check shape of array

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.array([1, 2, 3, 4], ndmin=5)
c = np.array((1, 2, 3, 4)) # tupple
d = np.array(((1, 2, 3, 4), (5, 6, 7, 8))) # 2-d tupple

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

(2, 4)
(1, 1, 1, 1, 4)
(4,)
(2, 4)


#### **Array Reshape**

`arr.`**`reshape`**`(n, n)`
- reshape dimension of array

`arr.`**`reshape`**`(n, -1, n)`
- let NumPy calculate the dimension
- only 1 dimension can be left unknown / be -1

`arr.`**`reshape`**`(-1)`
- flatten a n-d array to 1-d

Reshape 1-d to 2-d array

In [93]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

a = arr.reshape(2, 6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


Reshape 1-d to 3-d aray

In [94]:
b = arr.reshape(2, 3, 2)
print(b)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Reshape is a view; doesn't change the original array

In [95]:
print(arr.reshape(2,6).base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Unknown dimension

In [101]:
c = arr.reshape(2, 2, -1) # NumPy will calculate the suitable dim
print(c.shape)

d = arr.reshape(2, -1, 2) # -1 can be passed once at any dim
print(d.shape)

(2, 2, 3)
(2, 3, 2)


Flatten the array to 1-d

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

arr = arr.reshape(-1)

print(arr.shape)

(8,)


#### **Array Iterating**

`for x in arr:
    for y in x:
        for z in y:
            print(z)`
- loop through the ndarray to access individual element (number of for loop = nd)

`for x in np.`**`nditer`**`(arr):
    print(x)`
- use NumPy function nd iteration to loop through (whatever nd array of) elements

`for x in np.`**`nditer`**`(arr, flags=['buffered'], op_dtypes=['S]): print(x)`
- print individual elements in another dtypes

`for idx, x in np.`**`ndenumerate`**`(arr):
    print(idx, x)`
- use NumPy function nd enumerate to loop through the index and elements

Using for loop to iterate 1-d array

In [104]:
arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


Using for loop to iterate a 2-d array

In [123]:
arr = np.array([[1, 2], [3, 4]])

for x in arr: # loop the 2-d
    print(x)

for x in arr: # loop the 2-d
    for y in x: # loop the 1-d
        print(y)

[1 2]
[3 4]
1
2
3
4


Using for loop to iterate a 3-d array

In [124]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in arr: # loop 3-d
    print(x)

for x in arr: # loop 3-d
    for y in x: # loop 2-d
        print(y)

for x in arr: # loop the 3-d
    for y in x: # loop the 2-d
        for z in y: # loop the 1-d
            print(z)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[1 2]
[3 4]
[5 6]
[7 8]
1
2
3
4
5
6
7
8


Using nditer() to iterate the array

In [127]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6],[7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


Iterate array with different dtype

In [133]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']): # does not change dtype of arr so need buffered
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


Iterate array with different step size

In [135]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# for both elements, print every other element
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


Enumerated iteration of 1-d array

In [137]:
arr = np.array([1, 2, 3])

for i, x in np.ndenumerate(arr):
    print(i, x)

(0,) 1
(1,) 2
(2,) 3


Enumerated iteration of 2-d array

In [138]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for i, x in np.ndenumerate(arr):
    print(i, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


#### **Array Join**

`np.`**`concatenate`**`((arr1, arr2))` <- default
- vertical, dim remains the same

`np.`**`concatenate`**`((arr1, arr2), axis=1)`
- horiontal, dim remains the same

`np.`**`stack`**`((arr1, arr2))`
- vertical, dim increases by 1

`np.`**`stack`**`((arr1, arr2), axis=1)`
- horizontal, dim increases by 1

`np.`**`vstack`**`((arr1, arr2))`
- vertical, same with concatenate(axis=0)

`np.`**`hstack`**`((arr1, arr2))`
- horizontal, same with concatenate(axis=1)

`np.`**`dstack`**`((arr1, arr2))`
- depth stack, dim increase by 1

Concatenate 2-d arrays into a 2-d array

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(np.concatenate((arr1, arr2))) # vertical concat
print()
print(np.concatenate((arr1, arr2), axis=1)) # horizontal concat

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


Stack 2-d arrays into a 3-d array

In [179]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(np.stack((arr1, arr2)))
print()
print(np.stack((arr1, arr2), axis=1))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


Helper function stack

In [184]:
print(np.vstack((arr1, arr2))) # same with .concatenate(axis=0)
print()
print(np.hstack((arr1, arr2))) # same with .concatenate(axis=1)
print()
print(np.dstack((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


#### **Array Split**
`np.`**`array_split`**`(arr, 3)`
- split an array into a list of arrays of equal size (if possible)

`np.`**`hsplit`**`(arr, 3)`
- split an array horizontally

Split 1-d array

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

def show(arr):
    for x in arr:
        print(x)
    print()

show(np.array_split(arr,3))
show(np.array_split(arr, 4)) # NumPy will adjust from the end
show(np.array_split(arr,7)) # null if split into more than existing elements

[1 2]
[3 4]
[5 6]

[1 2]
[3 4]
[5]
[6]

[1]
[2]
[3]
[4]
[5]
[6]
[]



Split 2-d elements

In [214]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

show(np.array_split(arr, 3))
show(np.array_split(arr, 3, axis=1))
show(np.hsplit(arr, 3))

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]]

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]



#### **Array Search**

`np.`**`where`**`(arr == n)`
- return index/indices where the element value == n

`np.`**`searchsorted`**`(arr, n)`
- return the index where n should be inserted to keep the array sorted

`np.`**`searchsorted`**`(arr, n, side='right')`
- search from the right side

`np.`**`searchsorted`**`(arr, [n, m, p])`
- return index where n, m, p should be inserted

Find the index / indices where the value == x

In [217]:
arr = np.array(['a', 'c', 'b', 'c', 'a', 'c'])

print(np.where(arr == 'c'))

(array([1, 3, 5]),)


In [218]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(np.where(arr%2 == 0))

(array([1, 3, 5, 7]),)


Search sorted

In [228]:
arr = np.array([5, 6, 8, 9])
print(np.searchsorted(arr, 7)) # 7 should be inserted at index 2

arr = np.array([5, 6, 7, 8, 9])
print(np.searchsorted(arr, 7))
print(np.searchsorted(arr, 7, side='right')) # search from right side

2
2
3


Search sorted for multiple values

In [230]:
arr = np.array([1, 3, 5, 7])

print(np.searchsorted(arr, [2, 4, 6]))

[1 2 3]


#### **Array Sort**

`np.`**`sort`**`(arr)`

Sort array of integers

In [ ]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]
[3 2 0 1]


Sort array of strings

In [234]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


Sort array of booleans

In [235]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


Sort 2-d array

In [237]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


#### **Array Filter**

`filter = arr==2`

`arr[filter]`

- create a filter that store True / False of eeach element
- access it (element with False will be filtered out)

In [238]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

print(arr[x])

[41 43]


Example: return only elements > 42

In [239]:
filter_arr = []

for element in arr:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

print(filter_arr)
print(arr[filter_arr])

[False, False, True, True]
[43 44]


Example: return only the even elements

In [240]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = []

for element in arr:
    if element%2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

print(filter_arr)
print(arr[filter_arr])

[False, True, False, True, False, True, False]
[2 4 6]


Simplified filter directly from array

In [241]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

print(filter_arr)
print(arr[filter_arr])

[False False  True  True]
[43 44]


In [242]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr%2 == 0

print(filter_arr)
print(arr[filter_arr])

[False  True False  True False  True False]
[2 4 6]
